### ISSUE TITLE
Bug report: rem units are different, CAUSES an underscan.

### ISSUE THREAD

**Issue by mariomui** [0918nobita/obsidian-zhongwen-block#16]
marginTop: '-1.3rem', is too much.
Possibly setting    marginTop: -1em  would stop my pinyin from being truncated.
Also, possibly if you could cache some of the stuff so the execution of pinyin pro doesnt need to be excuted everytiem would prolly make rendering faster.
<img width="630" alt="Screen Shot 2023-11-15 at 4 58 20 AM" src="https://github.com/0918nobita/obsidian-zhongwen-block/assets/29618692/6645db1b-fc96-4195-958a-592e368b8556">

**Comment by 0918nobita** [comment]
Thank you for your report of the bug!

I haven't been able to reproduce it in my environment. Could you tell me more about your environment?
In my environment, pinyin is currently not truncated even if I write a code block at the beginning of document.
If `marginTop` is set to `-1em` , the gap between pinyin and Chinese characters seems too narrow.

<img width="397" alt="スクリーンショット 2023-11-16 18 36 15" src="https://github.com/0918nobita/obsidian-zhongwen-block/assets/8453302/2c43c7f3-e742-4969-bad0-f18cf3bd11a5">

Regarding the rendering performance improvement, I think it's a very good idea! I will try implementing a cache feature soon.

**Comment by mariomui** [comment]
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.1.1
	Snippets enabled: 7
	Restricted mode: off
	Plugins installed: 99
	Plugins enabled: 89
	
	It's generally a mac. i'll see if i can reproduce on an empty vault. 
	Most likely its a line issue. 
	Since you only scrape the text feed it through and then insert it all at once, the container doesn't ahve the computed calculation for the heights. Especially if do 
	你是誰
	我是誰
	
	espeically when i translate poems for example.

**Comment by 0918nobita** [comment]
I found the cause.
This bug only occurs in Editing views with Live Preview enabled.
I normally disable Live Preview, so I had not noticed this bug until now.

**Comment by 0918nobita** [comment]
@mariomui I have sent a pull request to fix this display bug.
I would be really grateful if you review this pull request.
