### ISSUE TITLE
Line breaks are not respected

### ISSUE THREAD

**Issue by orkunzozturk** [0918nobita/obsidian-zhongwen-block#75]
when there's a line break within the code block, resulting effect doesn't include those new lines. 

<img width="854" alt="image" src="https://github.com/0918nobita/obsidian-zhongwen-block/assets/80598196/41e1315a-fb4b-48cc-b425-6517a5d4afb8">

comes out like this:
<img width="849" alt="image" src="https://github.com/0918nobita/obsidian-zhongwen-block/assets/80598196/b44815a5-6b7b-4ca4-b83d-79589767c2bd">

**Comment by 0918nobita** [comment]
Thank you so much for taking the time to report this bug.
I plan to release a patch to fix this bug.

**Comment by 0918nobita** [comment]
@orkunzozturk I've just released patch `v0.6.1` ! The update should be available now.

**Comment by orkunzozturk** [comment]
works perfectly now. thank you for the fast patch.
